#!/usr/bin/env bash

(echo "| NLIMBS | Cycles Libjbn / GMP | Cycles difference | Overhead | Sd Libjbn / GMP     |";
 echo "|--------|---------------------|-------------------|----------|---------------------|";
 for limb in $(seq 1 8); do
   echo -n "| $limb "; 
   paste -d',' <(cut -d',' -f4,6 bin/fp/libjbn_exp_d_${limb}_1.out) \
               <(cut -d',' -f4,6 bin/fp/gmp_exp_d_${limb}_1.out) | \
     awk -F',' '{ printf "| %d / %d ", $2, $4
                  printf "| %d ", ($2 - $4)
                  printf "| %.2f %%", (($4-$2)/$2)*100
                  printf "| %.2f / %.2f ", $1, $3
                  printf "|\n" }'
  done
) | \
column -s'|' -o'|' -t

# TODO move this to scripts after refactor
